### ISSUE TITLE
Autostart doesn't work on Linux

### ISSUE THREAD

**Issue by hexion** [sidneys/desktop-dimmer#5]
Running on Ubuntu 16.04, with a gnome-flashback DE.

The application is installed by default on /opt/Desktop Dimmer/ if installed via the .deb package.
Selecting the "Launch on startup" setting does create an entry to auto start the application, but it fails to escape the space in the path, rendering the autostart unusable.

/opt/Desktop Dimmer/desktop-dimmer --hidden
should be
/opt/Desktop\ Dimmer/desktop-dimmer --hidden

Or even simpler, and considering the .deb package installs a link in /usr/local/bin, another option is to remove the path from the launcher command:
desktop-dimmer --hidden

**Comment by sidneys** [comment]
@hexion 
Thanks for the report. Please re-test with v2.5.0 and comment if this helps.

**Comment by hexion** [comment]
Same results.
I deleted the startup entry, updated the app to 2.5, then re-launched it.
A new startup entry was created:

Name: desktop-dimmer
Command: /opt/Desktop Dimmer/desktop-dimmer --hidden
Comment: desktop-dimmerstartup script

The scape in "Desktop Dimmer" is still not escaped, and so the application fails to auto start:

$ /opt/Desktop Dimmer/desktop-dimmer --hidden
bash: /opt/Desktop: No such file or directory

**Comment by sidneys** [comment]
@hexion 

Thanks for the follow-up. The issue has been addressed, please re-test with version [v2.5.1](https://github.com/sidneys/desktop-dimmer/releases) and post your results. Cheers.

**Comment by hexion** [comment]
I'm afraid that the fix put into 2.7.0 didn't fix the issue:

$ "/opt/Desktop Dimmer/desktop-dimmer --hidden"
bash: /opt/Desktop Dimmer/desktop-dimmer --hidden: No existe el archivo o
el directorio

The quote should be clossing after the file path, and not include the
parameters. eg)
$ "/opt/Desktop Dimmer/desktop-dimmer" --hidden

Hope that helps.

2017-02-27 19:01 GMT+01:00 Sidney <notifications@github.com>:

**Comment by sidneys** [comment]
@hexion 

The upstream module (node-auto-launch) is the culprit here, regardless of it having a near 100% test coverage. Hence we integrated a patched version of this library, in [v2.7.1](https://github.com/sidneys/desktop-dimmer/releases). Please re-test. Thanks for your accurate and timely reports.

**Comment by hexion** [comment]
I can confirm it is fixed now, the startup link created is now valid and autostart is working fine.
Thanks for fixing it!
