### ISSUE TITLE
Always pretty print the settings

### ISSUE THREAD

**Issue by romainrichard** [sidneys/desktop-dimmer#7]
I keep my Desktop Dimmer config in git and noticed a difference with regards to how the settings (`~/.config/Desktop Dimmer/Settings`) are saved to disk.

When changing the settings AND quitting Desktop Dimmer, the settings will be pretty printed, like so:
```
{
  "currentVersion": "2.5.0",
  "overlays": {
    "21691165392764930": {
      "alpha": 0.75,
      "color": "transparent"
    },
    "17607560531959042": {
      "alpha": 0,
      "color": "transparent"
    }
  },
  "launchOnStartup": true
}
```

But when changing the settings without quitting Desktop Dimmer, the settings will be saved on a single line, like so:
```
{"currentVersion":"2.5.0","overlays":{"21691165392764930":{"alpha":0.75,"color":"transparent"},"17607560531959042":{"alpha":0,"color":"transparent"}},"launchOnStartup":true}
```

Which results, for me, in git telling me there are changes every time I open Desktop Dimmer. Would be great if the settings could always be pretty printed so that doesn't happen.

**Comment by sidneys** [comment]
@romainrichard 
Thanks for the report. The issue has been addressed in v2.7.2.. Please re-test if the newest version and comment.

**Comment by romainrichard** [comment]
It seemed to be working at first but the issue is still there unfortunately.

Here's what I'm seeing, first I have Desktop Dimmer not running and check the status of my git repo:
```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
```
Then I start Desktop Dimmer and run the same command:
```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .config/Desktop Dimmer/Settings

no changes added to commit (use "git add" and/or "git commit -a")
```
Here's what the diff looks like:
```
$ git diff
diff --git a/.config/Desktop Dimmer/Settings b/.config/Desktop Dimmer/Settings
index fa04d33..8724b09 100644
--- a/.config/Desktop Dimmer/Settings   
+++ b/.config/Desktop Dimmer/Settings   
@@ -1,14 +1 @@
-{
-  "currentVersion": "2.7.2",
-  "overlays": {
-    "21691165392764930": {
-      "alpha": 0.2,
-      "color": "transparent"
-    },
-    "17607560531959042": {
-      "alpha": 0,
-      "color": "transparent"
-    }
-  },
-  "launchOnStartup": true
-}
+{"currentVersion":"2.7.2","overlays":{"21691165392764930":{"alpha":0.2,"color":"transparent"},"17607560531959042":{"alpha":0,"color":"transparent"}},"launchOnStartup":true}
```
Then I exit Desktop Dimmer and run `git status` again:
```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
```

**Comment by sidneys** [comment]
@romainrichard 
Thanks for the re-check. Weird issue. Can you please test whether the newly deployed v7.2.3 resolves it? It's not reproducible in our test VM (Ubuntu 16.10). Cheers, and keep those issue reports coming!

**Comment by romainrichard** [comment]
Looks like it works now because it only saves upon quitting Desktop Dimmer, which is fine by me, thanks for the quick update!
